apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: descheduler
  namespace: argocd
spec:
  project: descheduler
  destination:
    server: https://kubernetes.default.svc
    namespace: descheduler
  source:
    repoURL: https://kubernetes-sigs.github.io/descheduler
    chart: descheduler
    targetRevision: 0.*
    helm:
      valuesObject:
        schedule: "*/5 * * * *"
        deschedulerPolicy:
          profiles:
          - name: consolidation
            pluginConfig:
              - name: DefaultEvictor
                args:
                  nodeFit: true
              - name: HighNodeUtilization
                args:
                  thresholds:
                    cpu: 10
                    memory: 45
            plugins:
              balance:
                enabled:
                  - HighNodeUtilization
              evictor:
                enabled:
                  - DefaultEvictor
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
