apiVersion: tailscale.com/v1alpha1
kind: ProxyClass
metadata:
  name: spread-across-nodes
spec:
  metrics:
    enable: true
    serviceMonitor:
      enable: true
      labels:
        release: prometheus
  statefulSet:
    pod:
      topologySpreadConstraints:
        - maxSkew: 1
          topologyKey: kubernetes.io/hostname
          whenUnsatisfiable: ScheduleAnyway
          labelSelector:
            matchLabels:
              tailscale.com/parent-resource-type: ingress
