apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: grocy-config
  namespace: grocy
  annotations:
    recurring-job.longhorn.io/b2-daily-backup: enabled
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 5Gi
