#!/usr/bin/env python3
"""
Generate kube/hetzner-init-hook/configmap.yaml from the canonical hetzner/ source files.

Run by pre-commit whenever hetzner/update-cluster-config-secret.py or
hetzner/cloud-init-template.yaml changes. Exits 1 if the ConfigMap was
regenerated (so pre-commit reports the file as modified and the developer
stages the result before re-committing).

Usage:
    python3 hetzner/generate-configmap.py
"""
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).parent.parent
SCRIPT_SRC = REPO_ROOT / "hetzner" / "update-cluster-config-secret.py"
TEMPLATE_SRC = REPO_ROOT / "hetzner" / "cloud-init-template.yaml"
CONFIGMAP_OUT = REPO_ROOT / "kube" / "hetzner-init-hook" / "configmap.yaml"


def indent(text, spaces=4):
    prefix = " " * spaces
    return "\n".join(prefix + line if line else "" for line in text.splitlines())


def main():
    script_content = SCRIPT_SRC.read_text()
    template_content = TEMPLATE_SRC.read_text()

    configmap = f"""\
# Generated by hetzner/generate-configmap.py — do not edit directly.
# Edit hetzner/update-cluster-config-secret.py or hetzner/cloud-init-template.yaml,
# then run: python3 hetzner/generate-configmap.py
apiVersion: v1
kind: ConfigMap
metadata:
  name: hcloud-init-updater
  namespace: kube-system
data:
  update-cluster-config-secret.py: |
{indent(script_content)}
  cloud-init-template.yaml: |
{indent(template_content)}
"""

    CONFIGMAP_OUT.parent.mkdir(parents=True, exist_ok=True)
    existing = CONFIGMAP_OUT.read_text() if CONFIGMAP_OUT.exists() else None
    if existing == configmap:
        print("ConfigMap is up to date.")
        sys.exit(0)

    CONFIGMAP_OUT.write_text(configmap)
    print(f"Generated {CONFIGMAP_OUT.relative_to(REPO_ROOT)}")
    sys.exit(1)


if __name__ == "__main__":
    main()
