apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: slipway
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/fluv/kube.git
    path: slipway
    targetRevision: HEAD
    directory:
      recurse: true
  destination:
    namespace: slipway
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
