apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: statusgraph
  namespace: argocd
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: statusgraph
  project: default
  source:
    path: statusgraph
    repoURL: https://github.com/fluv/kube.git
    targetRevision: HEAD
    directory:
      recurse: true
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
