apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: telegram-trading
  namespace: argocd
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: telegram-trading
  project: default
  source:
    path: telegram-trading
    repoURL: https://github.com/fluv/kube.git
    targetRevision: HEAD
    directory:
      recurse: true
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
