apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: tf2-server
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: tf2
  project: default
  source:
    path: kube
    repoURL: https://github.com/fluv/tf2-server.git
    targetRevision: HEAD
    directory:
      recurse: true
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
