apiVersion: apps/v1
kind: Deployment
metadata:
  name: mariadb
  namespace: wiki-gsi
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mariadb
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: mariadb
    spec:
      nodeSelector:
        kubernetes.io/hostname: pi.home.arpa
      containers:
        - name: mariadb
          image: mariadb:10.11
          args:
            - --init-file=/etc/mysql/init.sql
          ports:
            - containerPort: 3306
          env:
            - name: MARIADB_AUTO_UPGRADE
              value: "1"
          volumeMounts:
            - name: db-data
              mountPath: /var/lib/mysql
            - name: db-init
              mountPath: /etc/mysql/init.sql
              subPath: db-init.sql
          livenessProbe:
            tcpSocket:
              port: 3306
            initialDelaySeconds: 60
            periodSeconds: 10
            timeoutSeconds: 5
          readinessProbe:
            tcpSocket:
              port: 3306
            initialDelaySeconds: 60
            periodSeconds: 10
            timeoutSeconds: 5
          resources:
            requests:
              cpu: 50m
              memory: 256Mi
            limits:
              memory: 512Mi
          securityContext:
            runAsUser: 999
            runAsGroup: 999
      volumes:
        - name: db-data
          persistentVolumeClaim:
            claimName: wiki-gsi-db
        - name: db-init
          configMap:
            name: wiki-gsi-settings
            items:
              - key: db-init.sql
                path: db-init.sql
---
apiVersion: v1
kind: Service
metadata:
  name: mariadb
  namespace: wiki-gsi
spec:
  type: ClusterIP
  selector:
    app: mariadb
  ports:
    - port: 3306
      targetPort: 3306
