apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: tempo
  namespace: monitoring
  labels:
    release: prometheus
spec:
  namespaceSelector:
    matchNames:
      - monitoring
  selector:
    matchLabels:
      app: tempo
  endpoints:
    - port: http
      path: /metrics
      interval: 30s
      scrapeTimeout: 10s
