apiVersion: v1
kind: ConfigMap
metadata:
  name: statusgraph-config
  namespace: statusgraph
data:
  config.yaml: |
    upstream:
      prometheus:
        url: "http://prometheus-kube-prometheus-prometheus.monitoring.svc.cluster.local:9090"
      alertmanager:
        url: "http://prometheus-kube-prometheus-alertmanager.monitoring.svc.cluster.local:9093"
    mapping:
      alerts:
        label_selector:
          - severity: "critical"
          - severity: "warning"
        service_labels:
          - service_id
        service_annotations:
          - statusgraph-node
      metrics: {}
